\" ear.1 - manual page for ear
\" Copyright 2012-2014 Bas Wijnen <wijnen@debian.org>
\" 
\" This program is free software: you can redistribute it and/or modify
\" it under the terms of the GNU Affero General Public License as
\" published by the Free Software Foundation, either version 3 of the
\" License, or (at your option) any later version.
\" 
\" This program is distributed in the hope that it will be useful,
\" but WITHOUT ANY WARRANTY; without even the implied warranty of
\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
\" GNU Affero General Public License for more details.
\" 
\" You should have received a copy of the GNU Affero General Public License
\" along with this program.  If not, see <http://www.gnu.org/licenses/>.

.TH EAR 1 2019-02-03 "Ear" "Ear"
.SH NAME
Ear \- dancing instructor helper

.SH SYNOPSIS
.B ear

.SH DESCRIPTION
.RI "Create a library in " "~/.local/share/ear/db/" " or " "/usr/share/ear/db/" ".  This will be made possible from the program.  Use the menu from the program to see all the keyboard shortcuts."

Try things.  This program only ever writes to database files, so you cannot remove any media files even when doing things wrong.

.SH AUTHOR
Ear was written by `Bas Wijnen <wijnen@debian.org> and Kasper Loopstra`
